package com.airbyte.charity.jwt;

public class JwtConfig {
    public static final String SECURE_KEY = "secureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKey";
}
